### ISSUE TITLE
Make better docs

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/norch#100]
Docs should be shorter and better

**Comment by tcurdt** [comment]
Shorter? What am I missing :)

Some docs using it via API and not via HTTP would be great. That's said just looking at

  https://github.com/fergiemcdowall/norch/blob/master/lib/norch.js

is a good start.

**Comment by tcurdt** [comment]
Ah, I see `norch` is just the server for 

  https://github.com/fergiemcdowall/search-index

...which has actually has decent docs :)

**Comment by eklem** [comment]
Yes =)
`search-index` has gotten shorter docs, but it still needs to be a little better. Let us know if you find documentation that could be done better, @tcurdt
