### ISSUE TITLE
A little too thin documentation?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#104]
Maybe we should put back in the command line options in the README.md? I can do it if you agree.

https://github.com/fergiemcdowall/norch/blob/master/lib/norch.js#L20-L26

**Comment by fergiemcdowall** [comment]
Yes, thats probably a good idea

**Comment by eklem** [comment]
Fixed with this commit: https://github.com/fergiemcdowall/norch/commit/b842ce28efb32d801394132c0ccd4668b0e5fb98
