### ISSUE TITLE
Internal add queue

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/norch#106]
At the moment if many users add documents at the same time the system will not calibrate properly. What is needed is an internal queue/batch system

**Comment by eklem** [comment]
:+1:

**Comment by megastef** [comment]
This might be of high interest for this project: 
Skiff from @pgte- Implementation of the Raft consensus algorithm in Node.js 
https://www.npmjs.com/package/skiff  
http://blog.yld.io/2014/10/27/skiff-raft-consensus-in-node-js/

**Comment by fergiemcdowall** [comment]
Hi @megastef and thanks for the link- interesting stuff. If I understand it correctly raft consensus allows key value ranges to be distributed among several nodes in a consistent manner? How could raft consensus be used in the context of `norch` (and/or `search-index`)?

**Comment by fergiemcdowall** [comment]
Concurrent indexing available in latest release
