### ISSUE TITLE
Phrase search is possible now, isn't it.

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#107]
Think this has been asked for before, but now we actually have "phrase search", don't we? Should go into the documentation. Mostly this is about how the frontend passes the query to norch/searc-index?

**Comment by fergiemcdowall** [comment]
Phrase search is in yes. Docs can definitely be improved- some kind of "cookbook" would work well I think

**Comment by eklem** [comment]
First, I'll just add it to the front page of the docs, and then an example of the query JSON with a phrase.

**Comment by eklem** [comment]
But maybe just the readme.md on `norch` and a bit more extensive on `search-index`?

**Comment by eklem** [comment]
And, you actually added it for `search-index` already: https://github.com/fergiemcdowall/search-index/blob/master/doc/search.md#phrase-search

**Comment by fergiemcdowall** [comment]
:+1:
