### ISSUE TITLE
Search Vietnamese words.

### ISSUE THREAD

**Issue by mrwen00** [fergiemcdowall/norch#109]
Hi there.
I'm now using your module 'Norch Forage'.
For instance, I have a text which has vietnamese words: 'tiếng việt'.
So I try to search it with the keywords 'tiếng việt', and it worked great.
But I want to search it by the keyword 'tieng viet'. I've tested but it hasn't been found.
Did your module support any feature for searching the vietnamese words like as above?
Thanks

**Comment by fergiemcdowall** [comment]
Hi @mrwen00 

Character normalisation isn't supported out of the box. You need to do the preprocessing outside of the library. Basically- duplicate the field in the input document, and normalise all the characters. You will then be able to search for both 'tiếng việt' and 'tieng viet'

**Comment by mrwen00** [comment]
@fergiemcdowall Thanks, I've got your idea.
