### ISSUE TITLE
search endpoint not working?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#111]
Indexed some stuff and doing `http://146.185.142.231:3030/search?q={AND:[{%22query%22:{%22*%22:[%22test%22]}}]}`, but getting this error
```JSON
{"code":"InternalError","message":"Unexpected token A"}
```
The matcher works though
![skjermbilde 2016-05-21 kl 08 46 27](https://cloud.githubusercontent.com/assets/236656/15446983/ec22c562-1f30-11e6-89ef-6cead8fd9157.png)

**Comment by fergiemcdowall** [comment]
Try

```javascript
q={
    query: {
      AND: [
        {'query': ['test'] }
      ]
    }
  }
```

(in this case you need a searchable field called 'query' containing the text "test")

**Comment by eklem** [comment]
I don't have a field `query`, but it errors at the A in AND: 

```
{"code":"InternalError","message":"Unexpected token A"}
```

The URL and query object:
```
http://146.185.142.231:3030/search?q={%22query%22:{AND:%20[{%22query%22:%20[%22test%22]}]}}
```

**Comment by fergiemcdowall** [comment]
```javascript
q={
    query: {
      AND: [
        {'*': ['*'] }
      ]
    }
  }
```

...should return everything

**Comment by eklem** [comment]
Got it working now, a little bug in the documentation on the first page:
```
http://localhost:3030/search?q={AND:[{"query":{"*":["usa"]}}]}
```
should be:
```
http://localhost:3030/search?q={"query":[{"AND":{"*":["usa"]}}]}
```

So, query/AND in wrong order, and `AND` should be `"AND"`. I can fix.

**Comment by eklem** [comment]
And, working now with 
```
http://146.185.142.231:3030/search?q={"query":{"AND":[{"*":["*"]}]}}
```
