### ISSUE TITLE
'/' endpoint appears to be dead

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/norch#114]
At the moment `/` leads to:

```javascript
{
"code": "ResourceNotFound",
"message": "/"
}
```

... it should really have a logo or reassuring message

**Comment by eklem** [comment]
Working now?
![skjermbilde 2016-09-07 kl 12 31 10](https://cloud.githubusercontent.com/assets/236656/18308945/11d8b30e-74f7-11e6-92a2-9e133c59f8b9.png)

Version 0.7.1

**Comment by fergiemcdowall** [comment]
quite possibly...
