### ISSUE TITLE
Error when post JSON object in body while creating index

### ISSUE THREAD

**Issue by sthawali** [fergiemcdowall/norch#115]
"Cannot read property 'document' of undefined"

**Comment by sthawali** [comment]
@fergiemcdowall Any update here ? I'm not able to post JSON in POST body.

**Comment by fergiemcdowall** [comment]
On holiday just now. Since the tests are failing, I can't just merge the pull request. Some further work needed.

**Comment by fergiemcdowall** [comment]
You should also include a test that expresses the functionality that you are adding to the library.

**Comment by fergiemcdowall** [comment]
If I understand this bug correctly, it is fixed in the upcoming `0.8.0` release
