### ISSUE TITLE
Problem with setting Access-Control-Allow-Origin address

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#119]
Both Norch and webserver with webpage querying the Norch-server is on the same server and domain name, only port differs. Norch is started with:

``` console
norch -i si-debug/ -c http://oppskrift.klemespen.com:80
```

And in the devtool console in Chrome I get this error message:

``` console
XMLHttpRequest cannot load http://oppskrift.klemespen.com:3030/search?q=%7B%22query%22%3A%5B%7B%22AND%…D%7D%5D%7D%5D%2C%22categories%22%3A%5B%7B%22field%22%3A%22tags%22%7D%5D%7D. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://oppskrift.klemespen.com' is therefore not allowed access.
```

The log shows that the Norch-server is queried:

``` json
{"name":"norch","hostname":"norch-test","pid":3977,"level":30,"req":{"method":"GET","url":"/search?q=%7B%22query%22%3A%5B%7B%22AND%22%3A%5B%7B%22*%22%3A%5B%22sjokoladekake%22%5D%7D%5D%7D%5D%2C%22categories%22%3A%5B%7B%22field%22%3A%22tags%22%7D%5D%7D","headers":{"host":"oppskrift.klemespen.com:3030","connection":"keep-alive","accept":"application/json, text/plain, */*","origin":"http://oppskrift.klemespen.com","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36","referer":"http://oppskrift.klemespen.com/norch/","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8,da;q=0.6,nb;q=0.4,sv;q=0.2"}},"req_id":"fa6f311e-0542-49be-b1f6-e574a4bd9838","msg":"REQUEST","time":"2016-09-14T19:09:25.103Z","v":0}
{"name":"norch","hostname":"norch-test","pid":3977,"level":30,"q":{"query":[{"AND":[{"*":["sjokoladekake"]}]}],"categories":[{"field":"tags"}]},"msg":"QUERY","time":"2016-09-14T19:09:25.108Z","v":0}
```

What am I doing wrong? Or doesn't the `-c`-flag work any more? Using Norch version 0.7.1

**Comment by eklem** [comment]
And the query that the webpage requests seems valid:
http://oppskrift.klemespen.com:3030/search?q=%7B%22query%22%3A%5B%7B%22AND%22%3A%5B%7B%22*%22%3A%5B%22sjokoladekake%22%5D%7D%5D%7D%5D%2C%22categories%22%3A%5B%7B%22field%22%3A%22tags%22%7D%5D%7D

**Comment by fergiemcdowall** [comment]
Its quite possible that problems with Access-Control-Allow-Origin  have crept back into the codebase since we dont have a test for it. It would be really great if we did have a test for it though.

**Comment by eklem** [comment]
That's my guess too. I have got this working with an earlier version.

**Comment by eklem** [comment]
Hmm, strange. Testing back to 0.16.5 and not getting it to work.

**Comment by eklem** [comment]
Still working, just a little hellish to set up. Port number doesn't seem to be a good idea when the port number is 80 and "*" doesn't seem to do anything good for domain name. Anyway, the positive thing is that it's working with:

norch -i si-debug/ -c http://oppskrift.klemespen.com

And testing from http://oppskrift.klemespen.com/norch

I thought I'd tried it all, but I hadn't. Go Norch 👍

**Comment by fergiemcdowall** [comment]
Hmmm- definitely need to set up an effective test for CORS

**Comment by eklem** [comment]
Got the comma-delimited list working too. Just needed to remove space, so:
```console
norch -c http://oppskrift.klikk.no,http://fiddle.jshell.net
```
And `*` works as the second value in a comma-delimited list, but not the first.

**Comment by eklem** [comment]
So, a little buggy?

**Comment by fergiemcdowall** [comment]
I've fixed this for now by having CORS set up in "permissive" mode- you should be able to access your norch from any webpage.

For more fine-grained tweaking, you can initialize a norch with the `cors` option, which corresponds to the restify `cors` option: http://restify.com/#cors

**Comment by fergiemcdowall** [comment]
Going to take the chance and close this issue :)
