### ISSUE TITLE
Hit highlighting via term-cluster: query-pipeline story

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#124]
We need support for hit highlighting via search-index' term-cluster.

**Comment by fergiemcdowall** [comment]
Agreed. And in the general case, allow query/result pipelines in Norch

**Comment by eklem** [comment]
synonyms (swap & expand) could be a nice pipeline part.

**Comment by eklem** [comment]
Thinking this could be something happening in the frontend and not norch / search-index. Going to create a small library for this: [hit-highlighter](https://github.com/eklem/hit-highlighter) which will be part of [daq-proc (document and query processing)](https://github.com/eklem/daq-proc). Closing for now, open again if you disagree 😄

**Comment by eklem** [comment]
Or use the term-cluster library, but just in the frontend, outside norch / search-index.
