### ISSUE TITLE
Should be able to run in a "machine readable" mode

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/norch#125]
In a scenario where norches are being provisioned, it should be possible to run Norch in a "machine readable" mode. This means that Norch should only output JSON objects, and not stuff like the startup logo. For all other cases the startup logo should be shown

**Comment by eklem** [comment]
This is closed, isn't it?

**Comment by fergiemcdowall** [comment]
Ah- tis indeed!
