### ISSUE TITLE
pageSize and offset snafu?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#126]
`pageSize` works as intended:
http://oppskrift.klemespen.com:3030/search?q={"query":{"AND":{"Varenavn":["champagne"]}},"pageSize":"3"}

But then I add `offset` and the result items suddenly grow:
http://oppskrift.klemespen.com:3030/search?q={"query":{"AND":{"Varenavn":["champagne"]}},"pageSize":"3","offset":"1"}

**Comment by fergiemcdowall** [comment]
That sounds like a bug :)

**Comment by eklem** [comment]
Mu guess is that it's in `search-index` since mostly what `norch` is doing is to pass stuff back and forth?

**Comment by fergiemcdowall** [comment]
Yes, most likely a bug in `search-index`

**Comment by fergiemcdowall** [comment]
There are now tests for offset and pagesize in search-index and norch, and everything seems to be passing.

I have squashed some minor, slightly related bugs lately, so maybe if you update to 0.8.7 things will start working. If not, I can take another look at it.

**Comment by eklem** [comment]
I'll do testing on the newest stuff, @fergiemcdowall

**Comment by eklem** [comment]
Have you pushed a norch-version that depends on the latest search-index?

**Comment by eklem** [comment]
published I mean, not pushed

**Comment by fergiemcdowall** [comment]
Yes- the Norch is now up to date with the latest (today's) search-index

**Comment by eklem** [comment]
Seems to still be there:
http://oppskrift.klemespen.com:3030/search?q=%7B%22query%22:%7B%22AND%22:%7B%22*%22:%5B%22champagne%22%5D%7D%7D,%22pageSize%22:%223%22%7D

http://oppskrift.klemespen.com:3030/search?q=%7B%22query%22:%7B%22AND%22:%7B%22*%22:%5B%22champagne%22%5D%7D%7D,%22pageSize%22:%223%22,%22offset%22:%221%22%7D

**Comment by fergiemcdowall** [comment]
Ok- can you pm me the dataset, or a snapshot?

**Comment by eklem** [comment]
I'll make a test-case, and get to re-test it cleanly in the same go!

**Comment by eklem** [comment]
If you do:
```console
npm install search-index-indexer
node node_modules/search-index-indexer/index.js -c https://raw.githubusercontent.com/eklem/search-index-indexer/master/config.json -d https://raw.githubusercontent.com/eklem/dataset-vinmonopolet/master/dataset-vinmonopolet-sparkling.str
mkdir norch-index
mv ./si/ ./norch-index/data/
norch -p 3030 -l silly -i norch-index
```

Then test these two links:
http://localhost:3030/search?q={"query":{"AND":{"Varenavn":["champagne"]}},"pageSize":"3"}
http://localhost:3030/search?q={"query":{"AND":{"Varenavn":["champagne"]}},"pageSize":"3","offset":"1"}

**Comment by fergiemcdowall** [comment]
Have reproduced the error by doing

```bash
npm install norch
curl https://raw.githubusercontent.com/eklem/dataset-vinmonopolet/master/dataset-vinmonopolet-sparkling.str > data.json
curl -X POST -d @data.json http://localhost:3030/add
```

Looking at it now...

**Comment by fergiemcdowall** [comment]
This one is a real "doh!"- The values of `offset` and `pageSize` have to be integers

So http://localhost:3030/search?q={"query":{"AND":{"Varenavn":["champagne"]}},"pageSize":3,"offset":1} works

It would be good if the library was a bit more forgiving and allowed `"1"` to be interpreted as `1`

**Comment by eklem** [comment]
I'll test!

**Comment by fergiemcdowall** [comment]
Need to push out the fix for doing stuff like `offset="2"` onto npm- just doing that now

**Comment by eklem** [comment]
Tested and working well here to 😃

**Comment by fergiemcdowall** [comment]
good! :)
