### ISSUE TITLE
What does the endpoint return?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#134]
Since there is now a lot of endpoints because of search-index new streamy nature, [I'm trying to create some helpers for my app](https://github.com/eklem/norch-vuejs-app/issues/38).

Is it so that the response from `norch` is either a stream (of JSON objects) or an actual JSON object?

**Comment by fergiemcdowall** [comment]
Any http request can be parsed as a stream or as a big lump. I think the easiest way to grok this is to have a look at [`request`](https://github.com/request/request), and also the new [fetch API](https://jakearchibald.com/2016/streams-ftw/) (good article by Jake Archibald)

**Comment by eklem** [comment]
Yes, I'm checking out different approaches there (also tested the fetch API a little), but I saw that [you wanted to have an object instead of string back for /docCount](https://github.com/fergiemcdowall/norch/issues/133). So the question is not what stuff is coded as, but what it contains.

**Comment by fergiemcdowall** [comment]
Yes, that's kind of a special case. If the response consists of just a number then that can be interpreted as a response code under some circumstances. Wrapping the number in an object removes the ambiguity
