### ISSUE TITLE
No contact with norch, is cors turned on?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#136]
Cors is turned on by default, isn't it? But how do I set it now to something different? Not from command line any more?

**Comment by fergiemcdowall** [comment]
Yes, CORS is turned on by default (so one Norch is accessible everywhere).

Having thought about it though, there should definitely be a way to fine tune CORS. Possibly the most robust way to implement this is to have a generic option for setting http headers.

**Comment by eklem** [comment]
Strange... I just upgraded to 8.5 (from 8.3 or something) and now I can't get contact with it through `http://domainname:3030/`, only through localhost

**Comment by fergiemcdowall** [comment]
Hmm- do you get an error message?

**Comment by eklem** [comment]
No, totally silent.

**Comment by fergiemcdowall** [comment]
OK- going to have a look at this tomorrow

**Comment by eklem** [comment]
I'm testing here a little too. Checking which versions it was working on. v0.8.1 was fine =)

**Comment by eklem** [comment]
It fails on [v0.8.2](https://github.com/fergiemcdowall/norch/commit/8eb13f6f7fc14c5ed227d62e5e6d60857229403)

**Comment by eklem** [comment]
Installed v0.8.5 and remove `, 127.0.0.1` from this line and it works again:
https://github.com/fergiemcdowall/norch/blob/master/lib/norch.js#L77

Not sure what that line does, so not submitting a PR.

**Comment by eklem** [comment]
Tested on the server as well. Both http://localhost:3030/ and http://127.0.0.1:3030/ in addition to what I was trying to fix: http://oppskrift.klemespen.com:3030/

I'll make a PR =)
