### ISSUE TITLE
Minor bug for the /totalHits and the /search endpoint ?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#142]
This works:
http://oppskrift.klemespen.com:3030/totalHits?q={"query":{"AND":{"*":["eple"]}}}

And this doesn't (gives you back all documents):
http://oppskrift.klemespen.com:3030/totalHits?q=[{"query":{"AND":{"*":["eple"]}}}]

Not sure why `q` should be able to be an array and not just an object? Same for /search ?

**Comment by fergiemcdowall** [comment]
Seems to work now?

**Comment by eklem** [comment]
I'll test. This was something not working in `search-index` that is fixed now?

**Comment by fergiemcdowall** [comment]
Yes, IIRC I fixed it in search-index
