### ISSUE TITLE
Support for availableFields

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#143]
It's getting closer =)
https://github.com/fergiemcdowall/search-index/blob/master/doc/API.md#availablefields

**Comment by fergiemcdowall** [comment]
Ah yes, should probably bubble that improvement up to norch :)

**Comment by eklem** [comment]
I'm getting really close to finishing `norch-vuejs-app` and combined this feature it could make for some really nice features over at [norch.io](http://norch.io).

**Comment by fergiemcdowall** [comment]
Available in 0.8.7
