### ISSUE TITLE
Categorize: Sorting a category on amount of document hits?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#145]
Is it possible to query /categorize and get back a stream sorted on amount of hits instead of by alphabet?

```url
http://oppskrift.klemespen.com:3030/categorize?q={"pageSize":10,"category":{"field":"Varetype"},"query":{"AND":{"*":["eple"]}}}
```
gives me:

```json
{"key":"*","value":315}
{"key":"brut","value":104}
{"key":"champagne","value":112}
{"key":"extra","value":15}
{"key":"musserende","value":203}
{"key":"rosé","value":16}
{"key":"sec","value":3}
{"key":"vin","value":203}
```

**Comment by fergiemcdowall** [comment]
Going to have a look at this. It would be great, and consistent, if `/categorize` could parse `offset`, `pageSize`, and `sort`

**Comment by eklem** [comment]
If sort also would work on regular search results, that would be sooo nice =). Then you could do alphabetical sorting on names, and geographical(numerical) sorting on distance
