### ISSUE TITLE
Available fields a bit to "streamy"?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#146]
Was thinking I should get a stream of objects back, but I get all the fields as one string. Is that correct?

http://test.klemespen.com:3030/availableFields

Indexed with latest search-index and latest norch server running.

**Comment by eklem** [comment]
```
*abvacidaromabitternesscodecolorcontainerSizecontainerTypecorkdescriptiondistrictfreshnessfullnessidimagemainCountrynamepricepricePerLiterproductSelectionproductTyperawMaterialstorablesugarsummarysweetnesstanninstastevintage
```

**Comment by fergiemcdowall** [comment]
Yes, it would probably be better if you could ask for an array. I'll look into it...

**Comment by eklem** [comment]
Doesn't need to be an array, but now it's just one long string without anything to split up on =)

**Comment by fergiemcdowall** [comment]
Have you tried doing it like this? https://github.com/fergiemcdowall/norch/blob/master/test/test.js#L72-L85

Either way- I think an array is a bit more accessible to people

**Comment by eklem** [comment]
Strange, this is the response I get from norch:
![screen shot 2017-03-03 at 12 55 59](https://cloud.githubusercontent.com/assets/236656/23550403/e5d6974e-0010-11e7-9918-b1c108243ac4.png)

**Comment by eklem** [comment]
Anyway =)

**Comment by fergiemcdowall** [comment]
Yes- this is a bit tricky because responses _are_ streams. (I think) it is streaming the fieldnames and showing you the end result. An array would be easier

**Comment by eklem** [comment]
But, when thinking about it, I think you should keep it as a streaming interface but just wrap it as objects where the value is the string/field-name. One reason is that I now have two response processors. One for streams and one for objects. Keeping it like that makes it clean.

Something like:
```
{"fieldname":"*"}
{"fieldname":"abv"}
{"fieldname":"acid"}
{"fieldname":"aroma"}
{"fieldname":"bitterness"}
{"fieldname":"code"}
{"fieldname":"color"}
{"fieldname":"containerSize"}
{"fieldname":"containerType"}
{"fieldname":"cork"}
{"fieldname":"description"}
{"fieldname":"district"}
{"fieldname":"freshness"}
{"fieldname":"fullness"}
{"fieldname":"id"}
{"fieldname":"image"}
{"fieldname":"mainCountry"}
...
```

**Comment by fergiemcdowall** [comment]
Yes- that makes sense

**Comment by eklem** [comment]
I'll look into fixing this

**Comment by eklem** [comment]
@fergiemcdowall I manage to re-write the output to be key/value as suggested above, but how do I get to define Content-Type = application/JSON?
