### ISSUE TITLE
Missing documentation on options?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#149]
Do we have any documentation for the `options` (possibilities + format) for running norch from a script?
```javascript
require('norch')(options, function(err, norch) {
  // Norch server started on http://localhost:3030 (or the specified host/port)
})
```

**Comment by eklem** [comment]
My guess is it's:
port, norchHome, logLevel and machineReadable ?

**Comment by fergiemcdowall** [comment]
Oh- thats a really good question...

**Comment by eklem** [comment]
I can test and see if I get something going, then document it.
