### ISSUE TITLE
How to format data before use /add ?

### ISSUE THREAD

**Issue by kanlidy** [fergiemcdowall/norch#151]
We need to format data and use the engine before the data add.

Is there anyway to do it?

**Comment by fergiemcdowall** [comment]
You mean to get the data into JSON? Or to change the structure of existing JSON? Or something else?

Could you be more specific?

**Comment by kanlidy** [comment]
No, I have a JSON data need to format when use your /add api, like a Middleware:

norch().then({here's format data Middleware}).call('add',function(){})

**Comment by fergiemcdowall** [comment]
Hmmm- that sounds like you are experiencing network problems, but Norch is working?

**Comment by kanlidy** [comment]
Norch is working!
