### ISSUE TITLE
Implementing for Electron JS and Nedb (local storage)

### ISSUE THREAD

**Issue by AlexVFornazieri** [fergiemcdowall/norch#155]
Hello everyone,

I'm looking for a search engine that can be integrated with nedb, in case I have Electron application whit nedb as local persistence.

I would like to be offering a more optimized search to users, by approaching words and ignoring punctuation marks as I describe in https://github.com/feathersjs/feathers/issues/822.

Is there any way for Noarch to be implemented for this purpose in this scenario?

Thank you all for the attention.

**Comment by fergiemcdowall** [comment]
Hi @AlexVFornazieri 

Probably the easiest way to do this is to use https://github.com/fergiemcdowall/search-index
