### ISSUE TITLE
check if /snapshot or /latestSnapshot is the issue

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#157]
Install the pullrequest-version and test. [Reference in documentation](https://github.com/fergiemcdowall/norch/blob/master/docs/API.md#latestsnapshot) talks about /snapshot, but the actual documentation shows it as [/createSnapshot.](https://github.com/fergiemcdowall/norch/blob/master/docs/API.md#createsnapshot).

Try to post on both...

A little investigation on [the error on this pull request](https://github.com/fergiemcdowall/norch/pull/156).

**Comment by eklem** [comment]
/createSnapshot should be called /snapshot in the documentation, or we should change the code + test. What do you think, @fergiemcdowall ? Not the cause of the error in the pull request though.

**Comment by eklem** [comment]
ToDo: Fire up Norch, try to create a snapshot, check the disk to see if folder + files are created.

**Comment by fergiemcdowall** [comment]
I wonder if `latestSnapshot` should be removed from the core. Its probably enough that `/snapshot` works?

**Comment by eklem** [comment]
Yes, we can add something like that if we get an actual use case.

**Comment by eklem** [comment]
Hmm, we have 
* snapshot (create a snapshot)
* latestSnapshot
* listSnapshots
