### ISSUE TITLE
Library Support

### ISSUE THREAD

**Issue by creativenoobie** [fergiemcdowall/norch#159]
Hey,

I was wondering if this library is still maintained and supported by the author?

I'm super excited to try this out!

**Comment by fergiemcdowall** [comment]
@creativenoobie Sort of kind of. I'm working on a rewrite at the moment, but Norch is fairly functional as it is.

**Comment by eklem** [comment]
Give it a try and we'll answer your questionsa the best we can, @creativenoobie . @fergiemcdowall has created it, and I'm an experienced user, and not that technical.

**Comment by creativenoobie** [comment]
@fergiemcdowall @eklem Thank you for your replies.

I hope rewrite will be totally kick ass! Looking forward for the implementation. I'm really excited for this since it literally strike off an headache of reinventing the wheel. 

Thank you for NORCH!
