### ISSUE TITLE
Forage running inside browser, added with bookmarklet

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#32]
Got an idea last week to use the browser as a virtual machine for Forage. Forage could then be added with a bookmarklet to any page. With some simple UI-stuff you could define the Forage Document Processor Adapter, set up rules for Forage Crawler, crawl (and process) and then possibly test-search with HTML5 local storage instead of levelDB. When the user is satisfied she or he could download the JSON-file with processed items + scripts for adding a search box, search result and navigators to a page.

The real benefit would be that the user would not need any server to test Forage and actually crawl a site. When page crawled the user can download JSON + setup-stuff or add it to a cloud service.

![foraging-01-page](https://cloud.githubusercontent.com/assets/236656/2758898/7a58d20a-c997-11e3-86bf-b365306b401a.png)
The user finds a page to crawl ...

![foraging-02-bookmarklet](https://cloud.githubusercontent.com/assets/236656/2758901/7d5fc896-c997-11e3-831e-836398903c8a.png)
... clicks the bookmarklet ...

![foraging-03-bookmarklet](https://cloud.githubusercontent.com/assets/236656/2758902/8038dae4-c997-11e3-87ee-4d7664b15600.png)
... that adds Forage JavaScript-stuff to the page ...

![foraging-04-foragin-pristine](https://cloud.githubusercontent.com/assets/236656/2758907/8356af6c-c997-11e3-8541-bb2d4b9f2dff.png)
... much like a browser plugin ...

![foraging-05-jquery-selector-test](https://cloud.githubusercontent.com/assets/236656/2758908/857e9570-c997-11e3-99f9-acd8eb6f34be.png)
... tests a jQuery selector satement ...

![foraging-06-jquery-selector-added](https://cloud.githubusercontent.com/assets/236656/2758909/880b8f28-c997-11e3-93f2-f91041c13982.png)
... and adds the field to the item when satisfied. This process is repeated until a full item is defined.

More to come on the crawl rule setup, test-search and downloading of data + adapter + crawl-rules

**Comment by eklem** [comment]
So, search-index is now browserifiable!
https://github.com/fergiemcdowall/search-index/pull/59
One down, many to go =)

**Comment by fergiemcdowall** [comment]
It pains to close a bug with so many good ideas and decent sketches, but this is definitely outwith the scope of Norch as a search engine. As you say @eklem `search-index` is now browserifiable, so toughening and documenting that functionality is the current goal with regards to "norch in browser"

**Comment by fergiemcdowall** [comment]
Would definitely make a cool project in its own repo.

**Comment by mewwts** [comment]
+1

2015-01-15 14:54 GMT+01:00 Fergus McDowall <notifications@github.com>:

**Comment by eklem** [comment]
No problem Fergus. Really happy search-index was browserifiable so fast, and that it actually happened! Nice to mock up the idea to make it better. Also, [Kimono](http://www.kimonolabs.com/) does the scraping part very well (partly by bookmarklet), so that fixes one step.

**Comment by eklem** [comment]
Got a minimal version of the indexing-part working over at [`norch-zapier-bookmarklet`](https://github.com/eklem/norch-zapier-bookmarklet/issues/5). And with norch.io this is bound to happen at some point =)

**Comment by eklem** [comment]
This one is possible to assemble with [nowcontent.xyz](https://github.com/eklem/nowcontent.xyz) pushing to i.e. Sanity.io
or JSONbin.io, and then have [this implementation of search-index](https://github.com/eklem/idx-tests/tree/master/async-index-and-search), but set it to fetch stuff from Sanity/JSONbin.
