### ISSUE TITLE
Chinese language support

### ISSUE THREAD

**Issue by znzn40** [fergiemcdowall/norch#39]
Is there any plan to support chinese language for forage?

**Comment by fergiemcdowall** [comment]
I recently rewrote a lot of this code, and some of my Chinese colleagues tell me that it is now working for Chinese text.

If there are still things that dont work, please submit a test case :)

**Comment by andyhu** [comment]
How can I define a Chinese word dictionary? Chinese (and Japanese) isn't like most western languages which use space to separate words. Instead there is a need to use a word segmentation tool. A good reference should be path https://github.com/olivernn/lunr.js/compare/master...codepiano:master which made lunr.js being able to support Chinese.

**Comment by fergiemcdowall** [comment]
@andyhu yes, the best strategy is to insert a separator into the text before you index it, and then specify that separator when you index it.
