### ISSUE TITLE
Logo!

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#41]
We need a new logo since Forage is dead and Norch is back. Dawn of the dead!

**Comment by MaxLans** [comment]
Hi @eklem, I would really go for the clustered logos. I just looked into this chat and I would still suggest to continue with the logo editing, for example:

https://cloud.githubusercontent.com/assets/236656/4548835/54538884-4e58-11e4-9f12-abd3221a4d8c.png

But just turn the background connected dots 90 degress to the left and you will have a nice logo. Apply the colors as shown here:

https://cloud.githubusercontent.com/assets/236656/4578295/bf989cf8-4fc3-11e4-9500-579df01fd837.png

First image on the left side is right color settings.

Can you initiate a new logo set with that, or apply me the source so i can do the rest?
also include the api text as a sublogo to show us the result.

Let's rock with Notch!

**Comment by eklem** [comment]
For now =)
<img width="741" alt="Screenshot 2020-07-31 at 10 02 24" src="https://user-images.githubusercontent.com/236656/89014005-2e225f80-d315-11ea-9525-f3cf21dd1839.png">
<img width="842" alt="Screenshot 2020-07-31 at 10 02 37" src="https://user-images.githubusercontent.com/236656/89014017-32e71380-d315-11ea-9873-4c472e700f08.png">

Feel free to open up again, @fergiemcdowall =)

Here are some more mockups I've made to show how associated modules could tie in.
<img width="1493" alt="Screenshot 2020-07-31 at 10 05 04" src="https://user-images.githubusercontent.com/236656/89014125-59a54a00-d315-11ea-9c08-28b493ad66a1.png">
