### ISSUE TITLE
Bookmark search tool

### ISSUE THREAD

**Issue by ccorcos** [fergiemcdowall/norch#44]
I've always wanted a better bookmark search tool. I have hundreds of them and I hate labeling them with searchable tags. I want to search their metadata! 

This looks like the perfect project to fork into a simple command line app.

Basically I just want to index my bookmarks (given some format: Safari, Chrome, Firefox, JSON, etc.) and then be able to search them. It would also be nice to save a snapshot. It will also be super badass to do this all through the command line too!

Anyways, I'm curious if anyone here wants to help me with this since I'm not terribly familiar with all the work that has been done here. I hope someone will agree that this is a pretty awesome tool. This is a very simple extension of what has already been implemented here.

I'd appreciate any help or any suggestions on how to get started.

Thanks

**Comment by fergiemcdowall** [comment]
Its a good idea that deserves a life of its own- good luck @ccorcos ! :smile:
