### ISSUE TITLE
Documentation: Search index and Norch from webtorrents

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#51]
A similar idea to the search engine as a bookmarklet. https://github.com/fergiemcdowall/norch/issues/32 But since the bookmarklet thingy is not the first to happen, it's good to describe some of the ideas more likely to happen.

If the "search engine running in your browser" works, how about the index, and maybe the search engine it self, as torrents/webtorrents. Then, the one making a webapp or webservice will almost need no server/hardware power at all. You only need a seeder of the app/search engine and search index.

**Comment by eklem** [comment]
Maybe a combination of webtorrents and the index as a github-project could work? Even if you could add, update or delete, the only thing a diff will do is add and/or delete key/value pairs. You could then have a main torrent and update torrents until you create a new main torrent (that'll make it faster for new users) every now and then.

**Comment by fergiemcdowall** [comment]
I really like this idea!

I propose that we simply say that Norch's replication interface can consume, and possibly seed, webtorrents

**Comment by eklem** [comment]
Hmm, and while we're at it. What if we could integrate it into the [webtorrents](https://github.com/feross/webtorrent) project for all publically available webtorrents:
- If you are seeding a file that's not in your index, your webtorrent client will create a search-index diff-file wrapped as a webtorrent, adding it to search index for everybody else using the webtorrent client.
- If you are leaching and can't get the full file, your webtorrent client will create a search-index diff-file deleting it from the index.

Every now and then all these diff's will be baked into an updated full search-index for webtorrent. No sure how all the pieces will fit together, but I think it's a good idea.

**Comment by eklem** [comment]
I guess you also don't need one original search index. Ony get small updates as webtorrents adding or deleting stuff.

**Comment by fergiemcdowall** [comment]
As far as I understand it- this is definitely possible, it just hasn't been done yet
