### ISSUE TITLE
Fix concurrent batch indexing

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/norch#57]
There are reports of documents disappearing when two or more batches are indexed concurrently (thanks @praveev)

The solution to this is probably to implement queuing functionality in Norch with https://github.com/learnboost/kue or similar.

**Comment by seti123** [comment]
kue uses redis, it's cool for systems that need to distribute job over multiple processes - not sure if you like to add this dependency. https://www.npmjs.com/package/queue might be better.

**Comment by fergiemcdowall** [comment]
#106 is related

**Comment by fergiemcdowall** [comment]
fixed

**Comment by eklem** [comment]
That's really nice!
