### ISSUE TITLE
Make documentation match example data

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#60]
This is a big job, but it would be really nice with documentation matching at least one sample set of data. That means it's much easier to test all the functionality and figure out how stuff is working.

**Comment by fergiemcdowall** [comment]
I think this is a part of a wider issue which is that some kind of website is needed. This is now underway.

**Comment by eklem** [comment]
When we find some interesting data, we'll scrape it with [Kimono](http://kimonolabs.com/). That way we'll have good data, fast.

**Comment by fergiemcdowall** [comment]
Yes, I am sure that publishing a Kimono-derived dataset would be relatively unproblematic especially as it becomes more dated.

**Comment by fergiemcdowall** [comment]
For the record, I use this set mostly, and this is also what the integration tests are set up to use: https://github.com/fergiemcdowall/reuters-21578-json

**Comment by mewwts** [comment]
Have you started creating a website @fergiemcdowall ?

**Comment by fergiemcdowall** [comment]
@mewwts Yes. Kind of.

**Comment by mewwts** [comment]
:+1:

**Comment by fergiemcdowall** [comment]
The docs are now much more generic, and redirect to `search-index` for the API stuff.
