### ISSUE TITLE
http://www.norchjs.net/ not reacable

### ISSUE THREAD

**Issue by JohnMcLear** [fergiemcdowall/norch#61]
url from readme.

Was considering integrating into Etherpad, doable?

**Comment by fergiemcdowall** [comment]
Totally doable with the underlying module- check out https://github.com/fergiemcdowall/search-index

**Comment by fergiemcdowall** [comment]
And yes, thanks for pointing that out, norchjs.net is down

**Comment by fergiemcdowall** [comment]
I am temporarily "solving" this problem by removing the URL from the README. New URL coming shortly
