### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by Enemico** [fergiemcdowall/norch#62]
While running  
sudo npm install -g norch
on ubuntu trusty

> leveldown@0.10.2 install /usr/local/lib/node_modules/norch/node_modules/search-index/node_modules/level/node_modules/leveldown
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/apparatus
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp

**Comment by fergiemcdowall** [comment]
From https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server

> Because of a conflict with another package, the executable from the Ubuntu repositories is called nodejs instead of node. Keep this in mind as you are running software.

See also http://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04

So, what you need to do is `sudo ln -s /usr/bin/nodejs /usr/bin/node` and it should work

**Comment by Enemico** [comment]
Thanks! This worked. 
Very nice to get an answer so fast.

**Comment by fergiemcdowall** [comment]
great! happy norching! :)
