### ISSUE TITLE
Use a utility lib. like Lo-dash or Underscore

### ISSUE THREAD

**Issue by mewwts** [fergiemcdowall/norch#64]
What does the great @fergiemcdowall think of introducing another dependency that will make life just a tad more easy for us? I vote yay! :+1:

**Comment by fergiemcdowall** [comment]
We just put a loada lo-dash into `search-index`, so @fergiemcdowall is in favour of this proposal! :)

**Comment by mewwts** [comment]
Cool! Lo-dash it is.
