### ISSUE TITLE
Time/date navigators

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#65]
To be able to set a time range (from time/date to time/date) as a filter/navigator would be great! You said Norch had something like this earlier? Or maybe this is an issue for `search-index`?

**Comment by fergiemcdowall** [comment]
Yes! We really need this!!

**Comment by mewwts** [comment]
Actually, I think indexing time-fields would be really cool! And they could be stored as int's I guess. :-)

**Comment by fergiemcdowall** [comment]
Needs to first be implemented in `search-index` and then bubbled up to `norch`

**Comment by mewwts** [comment]
True!

**Comment by eklem** [comment]
Guessing this is working elsewhere now, so could be closed here?

**Comment by fergiemcdowall** [comment]
Can be now be done by expressing time as a sortable value and then using range filters
