### ISSUE TITLE
Make Norch run on a Mirage unikernel

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#66]
Part of the fun with `Norch` is something as rear as a lightweight search engine. Still, you need a full OS, like OSX or Linux that Norch can run on top of. Now, the `search-index` can run in a browser, but to create a good user experience you need a server as well.

Maybe Mirage OS could help us creating a really small, snappy and cloud-ready unikernel? We need to figure out if Mirage will actually do this and make a howto description.
https://github.com/mirage/mirage

**Comment by eklem** [comment]
Have I understood MirageOS correct @Enemico ? Could Mirage be used in this way?

**Comment by Enemico** [comment]
I am honestly not in the position to answer to this. I haven't tried MirageOS yet. I just saw a presentation at 31c3 in Hamburg in december, and it inspired me, between other things, to think that could be something for Norch...

**Comment by eklem** [comment]
Good, so from what we know, it's not "not possible" :smile:

**Comment by fergiemcdowall** [comment]
This is a cool idea, but outwith the scope of the project

**Comment by eklem** [comment]
Jupp =)
