### ISSUE TITLE
Norch seems to be totally broken in git

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/norch#67]
The version in the git repo seems to be broken. The version in npm seems to be ok.

I cant run the cloned version on my mac.

**Comment by mewwts** [comment]
I pulled yesterday and it was working fine. However, this only
underlines the need for tests!

Den fredag 23. januar 2015 skrev Fergus McDowall <notifications@github.com>
følgende:

**Comment by fergiemcdowall** [comment]
hmmm... could you do `./bin/norch` on the command line?

**Comment by fergiemcdowall** [comment]
Have fixed `./bin/norch` by doing `require('../lib/norch.js')({'indexPath':'si'});`

I would like to make it so that `require('../lib/norch.js');` works again

**Comment by mewwts** [comment]
Oops, I might have pulled from my fork!
