### ISSUE TITLE
Posting data encoded as "application/json"

### ISSUE THREAD

**Issue by mewwts** [fergiemcdowall/norch#69]
For the time being, I think the only requests that are allowed are those that are form encoded. While working with #63 I began thinking that there is not much reason not to allow ```application/json```. However, I understand if it initally, for simplicity or some other reason I am unaware of, was chosen to stick with one?

**Comment by fergiemcdowall** [comment]
@mewwts what would be the best encoding? How would you approach this generally?

**Comment by mewwts** [comment]
I feel, but I might be wrong, that it makes more sense with ```application/json```, perhaps because it's mostly JSON that is being uploaded. It looks just as easy to parse as form-data. Anyways, not the highest priority question I guess, so we can just let it rest for a while.

**Comment by fergiemcdowall** [comment]
One of the big wins with form-data is that it is easy to make... forms! :)

But yes, I hear what you are saying, so I think the best option is to somehow have both.

**Comment by mewwts** [comment]
Yeah, wouldn't be that much work to maintain both actually.

**Comment by fergiemcdowall** [comment]
I have a feeling that we fixed this? If not, you can still POST JSON data, its just that it needs to be expressed in the "form" dialect
