### ISSUE TITLE
Delete the entire index

### ISSUE THREAD

**Issue by jwhscholten** [fergiemcdowall/norch#71]
I'm thinking on using norch as my primary data storage. I would simply drop the index and re-import new data on a daily basis. Is it possible to do this?

**Comment by fergiemcdowall** [comment]
Yes, that would work fine :)

**Comment by jwhscholten** [comment]
Great! In the documentation I only see an option for deleting items per docID. Is it possible to drop everything at once?

**Comment by fergiemcdowall** [comment]
Oh- thanks for pointing that out, I can see that the documentation needs to be improved.

Try the `/empty` endpoint, like for example `http://localhost:3030/empty`

**Comment by jwhscholten** [comment]
Brilliant! Thanks :+1:

**Comment by fergiemcdowall** [comment]
You can also just delete the data directory (defaults to `si`)
