### ISSUE TITLE
Acknowledge third party modules?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#72]
Norch consists of a lot of modules, and others create new modules that will fit into the Norch ecosystem. Maybe we should have a section in the readme for thrid-party modules, not vouching for them, but both aknowledging the effort, and help the users of Norch solving their problems?

**Comment by fergiemcdowall** [comment]
Module dependencies are covered in package.json, which in turn creates nice attribution lists. Im not sure that we need to duplicate that manually.

We should give more recognition to human beings, especially in package.json. Is there a utility that can harvest contributions (git commits, bug reports, other github activity) and then generate a `contributors` object in package.json?

**Comment by fergiemcdowall** [comment]
http://browsenpm.org/package.json

**Comment by eklem** [comment]
You're probably right. I still think it's a good idea, but this is maybe not the right place. Website/blog?

**Comment by fergiemcdowall** [comment]
You can see the dependencies here: https://www.npmjs.com/package/norch

Maybe they are autopublished on some other sites as well
