### ISSUE TITLE
Make it possible to bring up facets without specifying a search term

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/norch#73]
In other words, facets on the whole set

**Comment by eklem** [comment]
Yes! How do you think it should work? Show amount on each filter? Show search results without typing anything in the input box?

**Comment by fergiemcdowall** [comment]
Basically the `q` parameter should be optional

**Comment by fergiemcdowall** [comment]
This is fixed, since you can search for q=* and get all documents in the index
