### ISSUE TITLE
Unable to search for all documents (?q=*)

### ISSUE THREAD

**Issue by jstclair** [fergiemcdowall/norch#77]
After starting Norch and initialising the index, general searching works fine:

`curl http://localhost:3030/search?q=<term>`

but, contrary to the docs, searching for all items returns an empty result:

`curl http://localhost:3030/search?q=*`

Norch (started with -l silly) logs the following:

```js
{ query: { '*': [ '*' ] }, offset: 0, pageSize: 10 }
```
```console
GET /search?q=* 304 - - 13.778 ms
```

**Comment by fergiemcdowall** [comment]
Thanks for that @jstclair 

Looking into it...

**Comment by fergiemcdowall** [comment]
This should now be fixed in 0.4.17 (published to npm)

@jstclair how does it look for you?

**Comment by jstclair** [comment]
Unfortunately, same results. I've clone the repo (pre update) and can look at this once I'm home. Just for a bit more info:

Installed new version using:

```console
$ npm install norch@0.4.17
```

``` console 
$ ./node_modules/norch/bin/norch --version
0.2.3
```

A search like this works fine: `http://localhost:3030/search?q=og`

But this doesn't: `http://localhost:3030/search?q=*`

**Comment by fergiemcdowall** [comment]
Did you reindex? You need to delete your data dir and read everything in from scratch

(and I see that Norch is reporting the wrong version)

**Comment by fergiemcdowall** [comment]
just pushed a fix for the version thing

**Comment by jstclair** [comment]
Sorry, in between work and home. Yes, after emptying the index and re-indexing, the query works! Thanks!

**Comment by fergiemcdowall** [comment]
Goody!
