### ISSUE TITLE
Pass CORS as parameter

### ISSUE THREAD

**Issue by jstclair** [fergiemcdowall/norch#78]
Just a suggestion: you've hard-coded the CORS header, but it would probably be better to pass (an array of addresses) via the command-line. Either:

* default the array to localhost:8000 (and keep the current behavior), or 
* if no CORS endpoints are passed (array is empty), don't initialise CORS

(I'm sure this is related to your Angular demo - normally, wouldn't have noticed, but we proxy our local app running on 8000 via browser-sync running on 3000, so it blew up)

**Comment by fergiemcdowall** [comment]
Hehe- good idea and very perceptive! It was indeed a fast and quick workaround for the Angular demo I made last week :) This is on the todo list- please feel free to submit a pull request if your schedule allows.

**Comment by mewwts** [comment]
You beat me to this by 1 sec @fergiemcdowall! But I agree, this should def. be made more flexible.

**Comment by jstclair** [comment]
Sure, be happy to. You have any contributor guidelines/code formatting/CLA?

**Comment by fergiemcdowall** [comment]
Just follow the existing format as best you can and BE BOLD! :)
