### ISSUE TITLE
Geographical proximity filtering

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#79]
An easy, and good enough, way to do this could be within a square defined by two geographical points (top,left and bottom,right).

Guess this could be done similar to what we think the date/time-navigator could work:
https://github.com/fergiemcdowall/norch/issues/65

A two-field range navigator.

**Comment by fergiemcdowall** [comment]
Yes, this is fixed with range navigators

**Comment by fergiemcdowall** [comment]
This is strictly speaking fixed for filtering "box" cases, since you can specify ranges of latitude and longitude.
