### ISSUE TITLE
Start using milestones

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#83]
So, we should start using milestones and add issues to each of them? Then it's easier to show users/lurkers/developers that stuff is happening, and what that stuff consists of.

**Comment by fergiemcdowall** [comment]
Yes. Lets Do It™

**Comment by eklem** [comment]
:+1:

**Comment by eklem** [comment]
Great stuff!
https://github.com/fergiemcdowall/search-index/milestones/Version%200.5.0

**Comment by fergiemcdowall** [comment]
Aaaaaan heres one for norch: https://github.com/fergiemcdowall/norch/milestones/version%200.5.0

**Comment by eklem** [comment]
Coolio!
