### ISSUE TITLE
rocksdb as backend?

### ISSUE THREAD

**Issue by pianoboysai** [fergiemcdowall/norch#85]
Does norch have plan  to use rocksdb as backend in the future?
rocksdb is based on  leveldb,  it  did  lots of modifications so that has better performance.
https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks

**Comment by fergiemcdowall** [comment]
It could certainly be done, you would make the change in [search-index](https://github.com/fergiemcdowall/search-index), by switching out [levelup](https://github.com/rvagg/node-levelup) with [level-rocksdb](https://github.com/Level/level-rocksdb) on [this line](https://github.com/fergiemcdowall/search-index/blob/master/lib/search-index.js#L7)

**Comment by rusintez** [comment]
Would it be more elegant to _optionally_ accept an instance of leveldb in constructor params ? (to take advantage of leveldb plugins)

**Comment by rusintez** [comment]
Sorry, out of context here

**Comment by fergiemcdowall** [comment]
It would be cool to be able to choose your backend by sending a parameter on startup.

This would be useful since some DBs are better than others in certain scenarios. (http://influxdb.com/blog/2014/06/20/leveldb_vs_rocksdb_vs_hyperleveldb_vs_lmdb_performance.html)

**Comment by mewwts** [comment]
:+1:

**Comment by pianoboysai** [comment]
oh, cool, yes, the ability to choose backend  is very important, hope it could give param, so needn't change source.

**Comment by fergiemcdowall** [comment]
You can choose the backend in the underlying `search-index`lib, we just need to make that functionality available in Norch

**Comment by fergiemcdowall** [comment]
This now works by initialising an instance of `search-index` with the `levelup` of your choice and then using that `search-index` to initialise `norch`. The documentation could definitely be improved, but it does  work, at least insofar as `leveldown` switching works
