### ISSUE TITLE
Save Path 

### ISSUE THREAD

**Issue by sebastianetzkorn** [fergiemcdowall/norch#87]
Hello,
First I have to say thank you very much for norch . It works very well but I have a little question..

in which path or folder are the jason-files saved after uploading to norch (localhost).
I can't find a folder in documentation, but maybe I have overwritten sth. . 

Thank You and greetings,
Sebastian

**Comment by eklem** [comment]
You're using the [webinterface](http://localhost:3030/#/add) to index, or [norch-fetcher](https://github.com/fergiemcdowall/norch#norch-fetch) + [norch-indexer](https://github.com/fergiemcdowall/norch#norch-indexer)?
I'm guessing the webinterface. Then you'll get a binary index + logfiles under the catalog `si`. This catalog will either be in the folder you were when starting norch from the shell.

**Comment by fergiemcdowall** [comment]
Hi @sebastianetzkorn 

The files are stored in a leveldb instance. You can read them by using a leveldb reader on `si`, or by getting them by id with the `docid` parameter: `http://localhost.com:3030/getDoc?docID=` + docid

Maybe Norch could do more here. What kind of functionality would you like to see?

**Comment by eklem** [comment]
And you can get the JSON listed out like this:
http://localhost:3030/search?q=*

**Comment by sebastianetzkorn** [comment]
Thank you very much . I found the folder . I uploaded first 10k JSON objects with 
$ norch-indexer -d testdata/ -e http://localhost:3030/indexer      and then 100k. Works fine :) . But for the productive system we will need about 10  million JSON-Objects. Do you think the upload will work then and is Norch designed for so much data ?  
Thank you and greetings,
Sebastian

**Comment by fergiemcdowall** [comment]
Norch is best for small data. It can be scaled up to work for big data, and there are various strategies to do this. We do search engine consultancy in our day job, so if you have a budget, we can help you out.
