### ISSUE TITLE
Move from express to restify

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/norch#88]
http://mcavage.me/node-restify/

**Comment by eklem** [comment]
What's the idea?

**Comment by mewwts** [comment]
Restify is a framework for making REST APIs, while Express is a framework for making web applications. Since we have Norch bootstrap, we among other things don't need templating that express has.

**Comment by fergiemcdowall** [comment]
yep @mewwts , that was what i was thinking

**Comment by eklem** [comment]
Nice!

**Comment by fergiemcdowall** [comment]
done
