### ISSUE TITLE
Should we get rid of unneccesary use of this in norch.js?

### ISSUE THREAD

**Issue by mewwts** [fergiemcdowall/norch#90]

**Comment by fergiemcdowall** [comment]
Yes.

**Comment by mewwts** [comment]
I will take a look at this. Just need the tests to pass first.

**Comment by mewwts** [comment]
What was the purpose in the first place?

**Comment by fergiemcdowall** [comment]
There was some wierdness when instantiating norches from the command line. All the older norches would always switch over to the newest norches datastore. This is covered in the tests, so since the tests are passing, Im going to stick my neck out and say that it is fixed

**Comment by fergiemcdowall** [comment]
...and fixed without unnecessary thisification, thanks to your PR

**Comment by mewwts** [comment]
Cool!

**Comment by eklem** [comment]
this.shouldberemoved();
