### ISSUE TITLE
Full-text search, partial words and accents ?

### ISSUE THREAD

**Issue by jmzoda** [fergiemcdowall/norch#94]
Hello

- Could you give me a clue on full-text query search for misspelled words : 
http://localhost:3030/search?q=internt (instead of) http://localhost:3030/search?q=internet

- Also for partial word, quite close to misspelled : 
http://localhost:3030/search?q=ternet

- And for accents on words, example (hélicoptère for french translation of helicopter) if typed with and without accent. 
http://localhost:3030/search?q=hélicoptère and http://localhost:3030/search?q=helicoptere
I would like to avoid stripping all accents before indexing and querying.

Thank you

**Comment by fergiemcdowall** [comment]
1) full-text query search for misspelled words
There is no support for this at the moment. Its coming, but not straight away.

2) Also for partial word, quite close to misspelled
You could investigate the matcher functionality, which generates query suggestions. Currently it only works for "beginning with" matches, but we hope to introduce a levenstein matcher.

3) Accents on words
All search engines handle character normalisation in indexing/query pipelines consisting of processing stages. So stripping out accents on querying and indexing is basically what has to happen in one of these stages when indexing and then when querying

**Comment by jmzoda** [comment]
Hi @fergiemcdowall 
1. Then it's a new feature and it would be great to have it on Norch.
2. Checked and works only with beginsWith. 
3. OK. Understood.
Thank you for your answer.
