### ISSUE TITLE
Check out mikeal/spider?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#95]
Maybe we should check out the [spider](https://github.com/mikeal/spider) that @mikeal has created? It seems more mature and feature rich than [norch-fetch](https://github.com/fergiemcdowall/norch-fetch). If working well, it could be nice to document how to make it work with [norch](https://github.com/fergiemcdowall/norch) / [search-index](https://github.com/fergiemcdowall/search-index) in a best possible way.

**Comment by fergiemcdowall** [comment]
Yes, I have it starred and it does seem to be a good way to go

**Comment by eklem** [comment]
I'll give it a go in a while!

**Comment by fergiemcdowall** [comment]
This probably belongs in `norch-fetch`. I completely agree though.
