### ISSUE TITLE
Explaining build essentials - You need "make"

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#98]
I know this doesn't fully fit in the norch documentation, but it won't fit in any node and npm setup either, since it's not required. On Ubuntu I need to do `sudo apt-get install build-essential` for the `npm install norch` to succeed.

**Comment by fergiemcdowall** [comment]
Yes, I think thats a levelDB dependency? We did at one point have some doc about that under "know issues", but I removed it because it gave an impression of bugginess. Maybe we should put it back somehow?

**Comment by fergiemcdowall** [comment]
Yes, you do have to have a C compiler on your system to get levelDown to compile.

I am leaning towards not addressing this in the docs, since it is such a general issue and there are so many different ways to solve it. There are lots of things that wont work if you dont have a C compiler
